models/ContactForm.php
<?php

namespace app\models;
use Yii;
use yii\base\Model;


/**
 * ContactForm is the model behind the contact form.
 */
class ContactForm extends Model
{
    public $name;
    public $apellido;
    public $email;
    public $telefono;
    public $subject;
    public $body;
    public $reCaptcha;

    //public $verifyCode;


    /**
     * @return array the validation rules.
     */
    public function rules()
    {
        return [
            // name, email, subject and body are required
            [['name','apellido', 'email', 'subject', 'body'], 'required', 'message'=> 'Campo requerido'],
            ['telefono', 'integer'],
            // email has to be a valid email address
            ['email', 'email', 'message'=>'Introduzca un correo electrónico válido'],
            [['reCaptcha'], \himiklab\yii2\recaptcha\ReCaptchaValidator::className(), 'secret' => '6Le-MCUTAAAAACBCF-o0nbcT_FjuOJXUGNZd3Ow1']
            // verifyCode needs to be entered correctly
            //['verifyCode', 'captcha'],
        ];
    }

    /**
     * @return array customized attribute labels
     */
    public function attributeLabels()
    {
        return [
            //'verifyCode' => 'Codigo de verificación',
            'name'=>'Nombre: ',
            'apellido'=> 'Apellido: ',
            'email'=>'Email: ',
            'telefono'=>'Telefono: ',
            'subject'=>'Asunto: ',
            'body'=>'Comentario: ',
            
        ];
    }

    /**
     * Sends an email to the specified email address using the information collected by this model.
     * @param string $email the target email address
     * @return boolean whether the model passes validation
     */
    public function contact($email)
    {
        $content= '<p><b> Email: </b>'.$this->email.'</p>';
        $content.= '<p><b> Teléfono: </b>'.$this->telefono.'</p>';
        $content.= '<p><b> Nombre: </b>'.$this->name.'</p>';
        $content.= '<p><b> Apellido: </b>'.$this->apellido.'</p>';
        $content.= '<p><b> Asunto: </b>'.$this->subject.'</p>';
        $content.= '<p><b> Contenido: </b><br>'.$this->body.'</p>';
        if ($this->validate()) {
            Yii::$app->mailer->compose('@app/mail/layouts/html', ['content'=>$content])                    
                ->setTo($email)
                ->setFrom([$this->email => $this->name])
                ->setSubject($this->subject)
                ->setTextBody($this->body)
                ->send();

            return true;
        }
        return false;
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\Contacto;



class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        /*return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];*/
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionContacto()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');
            return $this->refresh();
        }
        return $this->render('contacto', [
            'model' => $model,
        ]);
    }
    
    public function actionEmpresa(){
        return $this->render('empresa') ;
    }
    
    public function actionProductos(){
        return $this->render('productos');
    }
    public function actionMarcas(){
        return $this->render('marcas');
    }
    
    public function actionMision()
    {
        return $this->render('mision');
    }
    
    
}

views/layouts/main.php
<?php
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="<?= Yii::$app->charset ?>">
        <meta name="viewport" content="width=device-width, initial-scale=1">
<?= Html::csrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>
        <meta charset="utf-8">
        <link href="css/master.css" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="css/owl.carousel.css" title="color1" media="all" />
        <link rel="stylesheet" type="text/css" href="css/owl.theme.css" title="color1" media="all" />
        <!--<link rel="stylesheet" type="text/css" href="css/owl.transitions.css" title="color1" media="all"/>-->
        <link href="css/font-awesome-animation.css" rel="stylesheet" />
    </head>
    <body data-scrolling-animations="true">
<?php $this->beginBody() ?>
        <div class="">
            <header id="this-is-top">
                <div class="container-fluid">
                    <div class="topmenu row"> 
                        <nav class="col-sm-offset-3 col-md-offset-4 col-lg-offset-4 col-sm-6 col-md-5 col-lg-5">
                        </nav>
                        <nav class="text-right col-sm-3 col-md-3 col-lg-3">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-google-plus"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-pinterest"></i></a>
                            <a href="#"><i class="fa fa-youtube"></i></a>
                        </nav>
                    </div>
                    <div class="row header">
                        <div class="col-sm-3 col-md-3 col-lg-3" style="">
                            <a href="index.php" id=""> <img src="img/logo.png" class="img-responsive radio-inline img-thumbnail" style="width: 300px; height: 150px; border-radius: 60px 20px 40px 20px; border-left: -10px;"/>
                            </a>                            
                        </div>
                        <div class="col-sm-offset-3 col-md-offset-1 col-lg-offset-1 col-sm-8 col-md-8 col-lg-8">
                            <div class="text-right header-padding">
                                <div class="h-block"><span>Llámanos</span>(55) 5035 2805</div>
                                <div class="h-block"><span>Correo</span>Interiglobal@com.mx</div>
                                <div class="h-block"><span>Horario laboral</span>Lun - Sab   |   8.00am - 19.00pm</div>
                                <a class="btn btn-success" href="#" style="margin-top: 10px;">Cotización gratuita</a>
                                <!--<a class="btn btn-success" href="#">GET A FREE QUOTE</a>-->
                            </div>
                            <a href="index.php"><h3 style="color: #262673; margin-top: 5px; margin-left: 10px;" class="col-lg-offset-0"><u>Interiglobal - México </u></h3></a>
                        </div>
                    </div>
                    <br>
                    <div id="main-menu-bg" ></div>  
                    <a id="menu-open" href="#"><i class="fa fa-bars"></i></a> 
                    
                    <?php
                    NavBar::begin([
                        'brandLabel' => '',
                        'brandUrl' => Yii::$app->homeUrl,
                        'options' => [
                            'class' => 'main-menu navbar-main-slide dropdown', 'style' => 'margin-bottom: -20px;'
                        ],
                    ]);
                    echo Nav::widget([
                        'options' => ['class' => 'nav navbar-nav navbar-main dropdown'],
                        'items' => [
                            ['label' => 'Inicio', 'url'=>['site/index']],
                            ['label' => 'Empresa', 'url'=>['site/empresa']],
                            ['label' => 'Productos', 'url'=>['site/productos']],
                            ['label' => 'Marcas/Modelos','url'=>['site/marcas']],
                            ['label' => 'Contacto', 'url'=>['site/contacto']],
                        ],
                    ]);
                    NavBar::end();
                    ?>                           
                    <a id="menu-close" href="#"><i class="fa fa-times"></i></a>
                </div>
            </header>       
<?= $content ?>                          
            <footer>
                <div class="color-part2"></div>
                <div class="color-part"></div>
                <div class="container-fluid">
                    <div class="row block-content">
                        <div class="col-sm-4 wow zoomIn" data-wow-delay="0.3s">
                            <a href="#" class="logo-footer"></a>
                            <p>Integer congue elit non semper laoreet sed lectu orc posuer nisl tempor sed felis ac mauris ellent esque ndu ca urna Integer vitae felis.</p>
                            <div class="footer-icons">
                                <a href="#"><i class="fa fa-facebook-square fa-2x"></i></a>
                                <a href="#"><i class="fa fa-google-plus-square fa-2x"></i></a>
                                <a href="#"><i class="fa fa-twitter-square fa-2x"></i></a>
                                <a href="#"><i class="fa fa-pinterest-square fa-2x"></i></a>
                                <a href="#"><i class="fa fa-vimeo-square fa-2x"></i></a>
                            </div>
                        </div>
                        <div class="col-sm-2 wow zoomIn" data-wow-delay="0.3s">
                            <h4>Nuestra ofertas</h4>
                            <nav>
                                <a href="#">Oferta #1</a>
                                <a href="#">Oferta #2</a>
                                <a href="#">Oferta #3</a>
                                <a href="#">Oferta #4</a>
                                <a href="#">Oferta #5</a>
                                <a href="#">Oferta #6</a>
                            </nav>
                        </div>
                        <div class="col-sm-2 wow zoomIn" data-wow-delay="0.3s">
                            <h4>MAIN LINKS</h4>
                            <nav>
                                <a href="index.php">Home</a>
                                <a href="index.php?r=site%2Fempresa">Empresa</a>
                                <a href="index.php?r=site%2Fproductos">Productos</a>
                                <a href="index.php?r=site%2Fmarcas">Marcas</a>
                                <a href="index.php?r=site%2Fcontacto">Contacto</a>
                            </nav>
                        </div>
                        <div class="col-sm-4 wow zoomIn" data-wow-delay="0.3s">
                            <h4>Información de contacto</h4>
                            Everyday is a new day for us and we work really hard to satisfy our customers everywhere.
                            <div class="contact-info">
                                <span><i class="fa fa-location-arrow"></i><strong>INTERIGLOBAL</strong><br>3608 NewHill Station Ave CA, Newyork 33102 </span>
                                <span><i class="fa fa-phone"></i>(55) 5035 2805</span>
                                <span><i class="fa fa-envelope"></i>Interiglobal@com.mx   |   interiglobal.com</span>
                                <span><i class="fa fa-clock-o"></i>LUN - SAB 8.00am - 19.00pm</span>
                            </div>
                        </div>
                    </div>
                    <div class="copy text-right"><a id="to-top" href="#this-is-top"><i class="fa fa-chevron-up"></i></a>Created by <a href="#" style="font-size: 110%;">BitEvolution </a> &copy; </div>
                </div>
            </footer>
        </div>
<?php $this->endBody() ?>
        
        <script src="js/owl.carousel.min.js"></script><!--SLIDER-->        
        <!--Theme-->
        <script src="js/jquery.smooth-scroll.js"></script><!--MENU DESPLEGABLE-->
        <script src="js/wow.min.js"></script><!--ANIMACIONES-->
        <script src="js/jquery.placeholder.min.js"></script><!--SLIDER INICIO-->
        <script src="js/theme.js"></script><!--SLIDER INICIO-->
        <script src='https://www.google.com/recaptcha/api.js'></script>
    </body>
    
</html>
<?php $this->endPage() ?>

views/layouts/site.php
<?php
/* @var $this \yii\web\View */
/* @var $content string */
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html>
	<head>
            <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		

		<link href="css/master.css" rel="stylesheet">

		<!-- SWITCHER -->
		<link rel="stylesheet" id="switcher-css" type="text/css" href="assets/switcher/css/switcher.css" media="all" />
		<link rel="alternate stylesheet" type="text/css" href="assets/switcher/css/color1.css" title="color1" media="all" />
		<link rel="alternate stylesheet" type="text/css" href="assets/switcher/css/color2.css" title="color2" media="all" />
		<link rel="alternate stylesheet" type="text/css" href="assets/switcher/css/color3.css" title="color3" media="all" />
		<link rel="alternate stylesheet" type="text/css" href="assets/switcher/css/color4.css" title="color4" media="all" />
		<link rel="alternate stylesheet" type="text/css" href="assets/switcher/css/color5.css" title="color5" media="all" />
		<link rel="alternate stylesheet" type="text/css" href="assets/switcher/css/color6.css" title="color6" media="all" />

		<!--[if lt IE 9]>
		<script src="//oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
		<script src="//oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->
	</head>
	<body data-scrolling-animations="true">
            <?php $this->beginBody() ?>
		<div class="sp-body">
			<header id="this-is-top">
				<div class="container-fluid">
					<div class="topmenu row">
						<nav class="col-sm-offset-3 col-md-offset-4 col-lg-offset-4 col-sm-6 col-md-5 col-lg-5">
							<a href="#">BUY NOW</a>
							<a href="#">read documentation</a>
							<a href="#">WHY US</a>
						</nav>
						<nav class="text-right col-sm-3 col-md-3 col-lg-3">
							<a href="#"><i class="fa fa-facebook"></i></a>
							<a href="#"><i class="fa fa-google-plus"></i></a>
							<a href="#"><i class="fa fa-twitter"></i></a>
							<a href="#"><i class="fa fa-pinterest"></i></a>
							<a href="#"><i class="fa fa-youtube"></i></a>
						</nav>
					</div>
					<div class="row header">
						<div class="col-sm-3 col-md-3 col-lg-3">
							<a href="01_home.html" id="logo"></a>
						</div>
						<div class="col-sm-offset-1 col-md-offset-1 col-lg-offset-1 col-sm-8 col-md-8 col-lg-8">
							<div class="text-right header-padding">
								<div class="h-block"><span>CALL US</span>1.800.987.6543</div>
								<div class="h-block"><span>EMAIL US</span>info@domain.com</div>
								<div class="h-block"><span>WORKING HOURS</span>Mon - Sat  8.00 - 19.00</div>
								<a class="btn btn-success" href="#">GET A FREE QUOTE</a>
							</div>
						</div>
					</div>
					<div id="main-menu-bg"></div>  
					<a id="menu-open" href="#"><i class="fa fa-bars"></i></a> 
					<nav class="main-menu navbar-main-slide">
						<ul class="nav navbar-nav navbar-main">
							<li class="dropdown">
								<a data-toggle="dropdown" class="dropdown-toggle border-hover-color1" href="01_home.html">HOME <i class="fa fa-angle-down"></i></a>
								<ul class="dropdown-menu">
									<li><a href="01_home.html">HOME 1</a></li>
									<li><a href="02_home.html">HOME 2</a></li>
								</ul>
							</li>
							<li class="dropdown">
								<a data-toggle="dropdown" class="dropdown-toggle border-hover-color1" href="05_services.html">OUR SERVICES <i class="fa fa-angle-down"></i></a>
								<ul class="dropdown-menu">
									<li><a href="05_services.html">OUR SERVICES 1</a></li>
									<li><a href="06_services.html">OUR SERVICES 2</a></li>
									<li><a href="07_services.html">OUR SERVICES 3</a></li>
								</ul>
							</li>
							<li class="dropdown">
								<a data-toggle="dropdown" class="dropdown-toggle border-hover-color1" href="03_about.html">ABOUT US <i class="fa fa-angle-down"></i></a>
								<ul class="dropdown-menu">
									<li><a href="03_about.html">ABOUT US 1</a></li>
									<li><a href="04_about.html">ABOUT US 2</a></li>
								</ul>
							</li>
							<li class="dropdown">
								<a data-toggle="dropdown" class="dropdown-toggle border-hover-color1" href="09_blog.html">Blog <i class="fa fa-angle-down"></i></a>
								<ul class="dropdown-menu">
									<li><a href="09_blog.html">Blog 1</a></li>
									<li><a href="10_blog.html">Blog 2</a></li>
								</ul>
							</li>
							<li><a href="11_blog-details.html">NEWS</a></li>
							<li><a href="12_contact.html">CONTACT</a></li>
							<li><a class="btn_header_search" href="#"><i class="fa fa-search"></i></a></li>
						</ul>
						<div class="search-form-modal transition">
							<form class="navbar-form header_search_form">
								<i class="fa fa-times search-form_close"></i>
								<div class="form-group">
									<input type="text" class="form-control" placeholder="Search">
								</div>
								<button type="submit" class="btn btn_search customBgColor">Search</button>
							</form>
						</div>
	                </nav>
					<a id="menu-close" href="#"><i class="fa fa-times"></i></a> 
				</div>
			</header>

			<div class="bg-image page-title">
				<div class="container-fluid">
					<a href="#"><h1>road transportation</h1></a>
					<div class="pull-right">
						<a href="01_home.html"><i class="fa fa-home fa-lg"></i></a> &nbsp;&nbsp;|&nbsp;&nbsp; <a href="06_services.html">Our services</a>&nbsp;&nbsp;|&nbsp;&nbsp; <a href="08_services-details.html">Road Transportation</a>
					</div>
				</div>
			</div>


			<div class="container-fluid block-content">
				hola mundo
			</div>

			<footer>
				<div class="color-part2"></div>
				<div class="color-part"></div>
				<div class="container-fluid">
					<div class="row block-content">
						<div class="col-xs-8 col-sm-4 wow zoomIn" data-wow-delay="0.3s">
							<a href="#" class="logo-footer"></a>
							<p>Integer congue elit non semper laoreet sed lectu orc posuer nisl tempor sed felis ac mauris ellent esque ndu ca urna Integer vitae felis.</p>
							<div class="footer-icons">
								<a href="#"><i class="fa fa-facebook-square fa-2x"></i></a>
								<a href="#"><i class="fa fa-google-plus-square fa-2x"></i></a>
								<a href="#"><i class="fa fa-twitter-square fa-2x"></i></a>
								<a href="#"><i class="fa fa-pinterest-square fa-2x"></i></a>
								<a href="#"><i class="fa fa-vimeo-square fa-2x"></i></a>
							</div>
							<a href="#" class="btn btn-lg btn-danger">GET A FREE QUOTE</a>
						</div>
						<div class="col-xs-4 col-sm-2 wow zoomIn" data-wow-delay="0.3s">
							<h4>WE OFFERS</h4>
							<nav>
								<a href="#">Sea Freight</a>
								<a href="#">Road Transportation</a>
								<a href="#">Air Freight</a>
								<a href="#">Railway Logistics</a>
								<a href="#">Packaging & Storage</a>
								<a href="#">Warehousing</a>
							</nav>
						</div>
						<div class="col-xs-6 col-sm-2 wow zoomIn" data-wow-delay="0.3s">
							<h4>MAIN LINKS</h4>
							<nav>
								<a href="01_home.html">Home</a>
								<a href="06_services.html">Our Services</a>
								<a href="04_about.html">About Us</a>
								<a href="07_services.html">News</a>
								<a href="10_blog.html">Shop</a>
								<a href="12_contact.html">Contact</a>
							</nav>
						</div>
						<div class="col-xs-6 col-sm-4 wow zoomIn" data-wow-delay="0.3s">
							<h4>CONTACT INFO</h4>
							Everyday is a new day for us and we work really hard to satisfy our customers everywhere.
							<div class="contact-info">
								<span><i class="fa fa-location-arrow"></i><strong>TRANSCARGO LTD.</strong><br>3608 NewHill Station Ave CA, Newyork 33102 </span>
								<span><i class="fa fa-phone"></i>1.800.987.6543</span>
								<span><i class="fa fa-envelope"></i>info@domain.com   |   quote@domain.com</span>
								<span><i class="fa fa-clock-o"></i>Mon - Sat  8.00 - 19.00</span>
							</div>
						</div>
					</div>
					<div class="copy text-right"><a id="to-top" href="#this-is-top"><i class="fa fa-chevron-up"></i></a>Created by <a href="#">Templines</a> &copy; 2015 TransCargo All rights reserved.</div>
				</div>
			</footer>
		</div>

		<!--Main  
		<script src="js/jquery-1.11.3.min.js"></script>
		<script src="js/jquery-ui.min.js"></script>
		<script src="js/bootstrap.min.js"></script>
		<script src="js/modernizr.custom.js"></script>
		<!--Switcher
		<!--<script src="assets/switcher/js/switcher.js"></script>
		<!--Owl Carousel
		<script src="assets/owl-carousel/owl.carousel.min.js"></script>
		<!--Contact form
		<script src="assets/contact/jqBootstrapValidation.js"></script> 
		<script src="assets/contact/contact_me.js"></script>
		<!-- SCRIPTS
	    <script type="text/javascript" src="assets/isotope/jquery.isotope.min.js"></script>
		<!--Theme
		<script src="js/jquery.smooth-scroll.js"></script>
		<script src="js/wow.min.js"></script>
		<script src="js/jquery.placeholder.min.js"></script>
		<script src="js/smoothscroll.min.js"></script>
		<script src="js/theme.js"></script>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/site/historia.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'HISTORIA';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="bg-image page-title">
        <div class="container-fluid">
           <h1><?= Html::encode($this->title) ?></h1>
            <div class="pull-right">
                <a href="#"><i class="fa fa-home fa-lg"></i></a> &nbsp;&nbsp;|&nbsp;&nbsp; <a href="06_services.html">Nuestros servicios</a>
            </div>
        </div>
</div>

<div class="container-fluid block-content">
				<div class="row">
					<div class="col-sm-6 wow fadeInLeft" data-wow-delay="0.3s">
						<h1>AGASA <br> </h1>
                                                <div class="text-justify" style="font-size: 125%">
                                                <p>Con experiencia de 18 años en el mercado a nivel Nacional que nos respaldan en conversión de GASOLINA a GAS.                                               Hemos cubierto el mercado principal de la ciudad y el estado.

<p>Gracias a nuestra labor y empeño nos hicimos acreedores a la distribución de la marca más prestigiada a nivel mundial BRC de
    origen Europeo (Italia), con presencia en más de 80 países en el mundo.Además contamos con SERVICIO A UNIDADES CON SISTEMA DE GAS, REFACCIONES BRC E IMPCO, DICTAMEN NOM-
005, TODO LO RELACIONADO A GAS AUTOMOTRIZ Y MONTACARGAS.</p>
                                          </div>
					</div>
					<div class="col-sm-6 wow fadeInRight" data-wow-delay="0.3s">
						<img class="full-width" src="img/principal4.jpeg" alt="Img">
						<p>Edificio donde inició AGASA</p>
					</div>
				</div>
			</div>